---
name: distro containers

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:
    types: rebuild
  workflow_dispatch:
    inputs:
      git-ref:
        required: false

jobs:
  distros:
    name: "Container ${{ matrix.distro }}"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        distro: [
          "alpine",
          "quay.io/centos/centos:stream9",
          "debian:10", "debian:11", "debian:12",
          "fedora:35", "fedora:36", "fedora:37", "fedora:38",
          "fedora:39", "fedora:40", "fedora:41",
          "opensuse/leap",
          "ubuntu:20.04", "ubuntu:22.04", "ubuntu:24.04", "ubuntu:24.10",
          "gentoo/stage3"
        ]
    steps:
      - name: checkout
        uses: "actions/checkout@v3"
      - name: Define tag
        run: |
           suffix="${distro//:/_}"
           suffix="${suffix////_}"
           echo "tag=certsysstore:$suffix" >> $GITHUB_ENV
        env:
           distro: ${{ matrix.distro }}
      - name: Create Dockerfile
        run: |
          cat > Dockerfile << EOF
          FROM ${{ matrix.distro }}
          COPY .github/provision.sh /
          RUN /provision.sh
          VOLUME /workdir
          WORKDIR /workdir
          COPY .github/entry.sh /
          ENTRYPOINT /entry.sh
          EOF
      - name: "Build container ${{ matrix.distro }}"
        run: |
           set -xe
           docker build . -f Dockerfile -t ${{ env.tag }}
      - name: "Run container ${{ matrix.distro }}"
        run: |
          set -xe
          docker run --volume $(pwd):/workdir ${{ env.tag }}
